#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom -b &
polybar -rq main &
xsetroot -cursor_name left_ptr &

bspc monitor -d Web Term Steam Spotify Discord

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         2
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam state=floating
bspc rule -a Spotify state=floating
bspc rule -a Discord state=floating
